---
AWSTemplateFormatVersion: '2010-09-09'
Description: Custom resource to enable using Terraform in CloudFormation
Resources:
  TerraFormExecuteFunction:
    Type: AWS::Lambda::Function
    Properties:
      Code:
        ZipFile: |
          import boto3
          import time
          import json
          import cfnresponse
          import subprocess
          import os
          import sys

          def handler(event, context):
              print("Received event: " + json.dumps(event, indent=2))

              terraform_working_directory = '/tmp/terraform_files'

              # TODO: sha check
              subprocess.check_output('curl -o /tmp/terraform.zip https://releases.hashicorp.com/terraform/0.10.0/terraform_0.10.0_linux_amd64.zip', shell=True)
              subprocess.check_output('unzip -o -d /tmp /tmp/terraform.zip', shell=True)
              #print(subprocess.check_output('/tmp/terraform version', shell=True))

              if event['RequestType'] == 'Delete':
                  cfnresponse.send(event=event, context=context, responseStatus=cfnresponse.SUCCESS, responseData={}, physicalResourceId=event['LogicalResourceId'])
                  return

              # write terraform file
              os.makedirs(terraform_working_directory, exist_ok=True)
              open(os.path.join(terraform_working_directory, 'terraform.tf'), 'w').write(event['ResourceProperties']['Terraform'])

              try:
                # https://github.com/hashicorp/terraform/issues/12971
                subprocess.check_output('rm -fr .terraform/terraform.tfstate', shell=True, cwd=terraform_working_directory)
                subprocess.check_output('/tmp/terraform init', shell=True, cwd=terraform_working_directory)
                print(subprocess.check_output('/tmp/terraform apply', stderr=subprocess.STDOUT, shell=True, cwd=terraform_working_directory))

                terraform_outputs = json.loads(subprocess.check_output('/tmp/terraform output -json', stderr=subprocess.STDOUT, shell=True, cwd=terraform_working_directory))
                response_data = {key: value['value'] for key, value in terraform_outputs.items()}

                cfnresponse.send(event=event, context=context, responseStatus=cfnresponse.SUCCESS, responseData=response_data, physicalResourceId=event['LogicalResourceId'])

              except subprocess.CalledProcessError as exc:
                print("Status : FAILED", exc.returncode, exc.output)
                # TODO: add response data
                cfnresponse.send(event=event, context=context, responseStatus=cfnresponse.FAILED, responseData={}, physicalResourceId=event['LogicalResourceId'])
                return


      Handler: index.handler
      Runtime: python3.6
      Timeout: 300
      Role: !GetAtt TerraFormExecuteFunctionRole.Arn

  TerraFormStateStorage:
    Type: AWS::S3::Bucket
    Properties:
      VersioningConfiguration:
        Status: Enabled

  TerraFormExecuteFunctionRole:
    Type: AWS::IAM::Role
    Properties:
      AssumeRolePolicyDocument:
        Version: '2012-10-17'
        Statement:
        - Effect: Allow
          Principal:
            Service: lambda.amazonaws.com
          Action: sts:AssumeRole
      ManagedPolicyArns:
      - arn:aws:iam::aws:policy/service-role/AWSLambdaBasicExecutionRole
      Policies:
      - PolicyName: AllowWriteAndReadTerraformStateStorage
        PolicyDocument:
          Version: '2012-10-17'
          Statement:
          - Effect: Allow
            Action:
            - s3:Put*
            - s3:Get*
            - s3:List*
            Resource:
            - !GetAtt TerraFormStateStorage.Arn
            - !Sub '${TerraFormStateStorage.Arn}/*'

Outputs:
  TerraFormExecuteFunctionRole:
    Description: IAM Role to execute Terraform
    Value: !Ref TerraFormExecuteFunctionRole
